# Generated by Django 5.1 on 2024-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('poem', 'Стихотворение'), ('song', 'Песня'), ('story', 'Рассказ')], default='song', max_length=10)),
                ('lyrics', models.TextField()),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
